### ISSUE TITLE
Binary XML file line #14: Binary XML file line #14: Error inflating class 

### ISSUE THREAD

**Issue by wiliarko** [eltohamy/material-hijri-calendarview#17]
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.github.eltohamy.materialhijricalendarview.sample"
        minSdkVersion 14
        targetSdkVersion 27
        versionCode project.ext.versionCodeInt
        versionName version
    }
}
repositories {
    maven {
        url 'https://dl.bintray.com/el-tohamy/maven/'
    }
}
dependencies {
    // You should use the commented out line below in you're application.
    // We depend on the source directly here so that development is easier.
    implementation "com.android.support:support-v4:27.1.1"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation project(':library')
    implementation 'com.github.eltohamy:material-hijri-calendarview:1.1.1'
    implementation group: 'com.github.msarhan', name: 'ummalqura-calendar', version: '1.1.7'
//    implementation 'com.github.msarhan:ummalqura-calendar:1.1.7'

    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}`

2019-04-01 15:11:07.536 5033-5033/com.github.eltohamy.materialhijricalendarview.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.eltohamy.materialhijricalendarview.sample, PID: 5033
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.eltohamy.materialhijricalendarview.sample/com.github.eltohamy.materialhijricalendarview.sample.BasicActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2841)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
     Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:651)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.github.eltohamy.materialhijricalendarview.sample.BasicActivity.onCreate(BasicActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:7074)
        at android.app.Activity.performCreate(Activity.java:7065)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2794)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.util.MissingResourceException: Can't find bundle for base name com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData, locale in_ID
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1558)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1381)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:847)
        at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.initializeData(UmmalquraDateFormatSymbols.java:91)
        at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.<init>(UmmalquraDateFormatSymbols.java:66)
2019-04-01 15:11:07.532 430-430/? E/SurfaceFlinger: getUniqueId not supported on VirtualDisplaySurface
2019-04-01 15:11:07.538 5033-5033/com.github.eltohamy.materialhijricalendarview.sample E/AndroidRuntime:     at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.getDisplayName(UmmalquraCalendar.java:325)
        at com.github.eltohamy.materialhijricalendarview.format.DateFormatTitleFormatter.format(DateFormatTitleFormatter.java:42)
        at com.github.eltohamy.materialhijricalendarview.TitleChanger.doChange(TitleChanger.java:68)
        at com.github.eltohamy.materialhijricalendarview.TitleChanger.change(TitleChanger.java:51)
        at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.updateUi(MaterialHijriCalendarView.java:373)
        at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.access$600(MaterialHijriCalendarView.java:67)
        at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView$2.onPageSelected(MaterialHijriCalendarView.java:184)
        at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1935)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:659)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:617)
        at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.setCurrentDate(MaterialHijriCalendarView.java:700)
        at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.setCurrentDate(MaterialHijriCalendarView.java:688)
        at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.<init>(MaterialHijriCalendarView.java:333)
        	... 26 more

**Comment by edsusantoo** [comment]
##---------------Start: proguard configuration for Hijiriah Date  ----------
-keep class com.github.eltohamy**
-keepclassmembers class com.github.eltohamy** {*;}

-keep class com.github.msarhan**
-keepclassmembers class com.github.msarhan** {*;}
##---------------End: proguard configuration for Hijiriah Date  ----------

try to add this in proguard rules 

> `apply plugin: 'com.android.application'
> 
> android {
> compileSdkVersion 27
> buildToolsVersion '27.0.3'
> 
> ```
> defaultConfig {
>     applicationId "com.github.eltohamy.materialhijricalendarview.sample"
>     minSdkVersion 14
>     targetSdkVersion 27
>     versionCode project.ext.versionCodeInt
>     versionName version
> }
> ```
> 
> }
> repositories {
> maven {
> url 'https://dl.bintray.com/el-tohamy/maven/'
> }
> }
> dependencies {
> // You should use the commented out line below in you're application.
> // We depend on the source directly here so that development is easier.
> implementation "com.android.support:support-v4:27.1.1"
> implementation 'com.android.support:appcompat-v7:27.1.1'
> implementation 'com.android.support:recyclerview-v7:27.1.1'
> implementation project(':library')
> implementation 'com.github.eltohamy:material-hijri-calendarview:1.1.1'
> implementation group: 'com.github.msarhan', name: 'ummalqura-calendar', version: '1.1.7'
> // implementation 'com.github.msarhan:ummalqura-calendar:1.1.7'
> 
> ```
> implementation 'com.jakewharton:butterknife:8.8.1'
> annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
> ```
> 
> }`
> 
> 2019-04-01 15:11:07.536 5033-5033/com.github.eltohamy.materialhijricalendarview.sample E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.github.eltohamy.materialhijricalendarview.sample, PID: 5033
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.eltohamy.materialhijricalendarview.sample/com.github.eltohamy.materialhijricalendarview.sample.BasicActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2841)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919)
> at android.app.ActivityThread.-wrap11(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:176)
> at android.app.ActivityThread.main(ActivityThread.java:6656)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
> Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView
> Caused by: java.lang.reflect.InvocationTargetException
> at java.lang.reflect.Constructor.newInstance0(Native Method)
> at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
> at android.view.LayoutInflater.createView(LayoutInflater.java:651)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
> at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
> at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
> at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
> at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
> at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
> at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
> at com.github.eltohamy.materialhijricalendarview.sample.BasicActivity.onCreate(BasicActivity.java:38)
> at android.app.Activity.performCreate(Activity.java:7074)
> at android.app.Activity.performCreate(Activity.java:7065)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2794)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2919)
> at android.app.ActivityThread.-wrap11(Unknown Source:0)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
> at android.os.Handler.dispatchMessage(Handler.java:106)
> at android.os.Looper.loop(Looper.java:176)
> at android.app.ActivityThread.main(ActivityThread.java:6656)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> Caused by: java.util.MissingResourceException: Can't find bundle for base name com.github.msarhan.ummalqura.calendar.text.UmmalquraFormatData, locale in_ID
> at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1558)
> at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1381)
> at java.util.ResourceBundle.getBundle(ResourceBundle.java:847)
> at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.initializeData(UmmalquraDateFormatSymbols.java:91)
> at com.github.msarhan.ummalqura.calendar.UmmalquraDateFormatSymbols.(UmmalquraDateFormatSymbols.java:66)
> 2019-04-01 15:11:07.532 430-430/? E/SurfaceFlinger: getUniqueId not supported on VirtualDisplaySurface
> 2019-04-01 15:11:07.538 5033-5033/com.github.eltohamy.materialhijricalendarview.sample E/AndroidRuntime: at com.github.msarhan.ummalqura.calendar.UmmalquraCalendar.getDisplayName(UmmalquraCalendar.java:325)
> at com.github.eltohamy.materialhijricalendarview.format.DateFormatTitleFormatter.format(DateFormatTitleFormatter.java:42)
> at com.github.eltohamy.materialhijricalendarview.TitleChanger.doChange(TitleChanger.java:68)
> at com.github.eltohamy.materialhijricalendarview.TitleChanger.change(TitleChanger.java:51)
> at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.updateUi(MaterialHijriCalendarView.java:373)
> at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.access$600(MaterialHijriCalendarView.java:67)
> at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView$2.onPageSelected(MaterialHijriCalendarView.java:184)
> at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1935)
> at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:659)
> at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
> at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:617)
> at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.setCurrentDate(MaterialHijriCalendarView.java:700)
> at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.setCurrentDate(MaterialHijriCalendarView.java:688)
> at com.github.eltohamy.materialhijricalendarview.MaterialHijriCalendarView.(MaterialHijriCalendarView.java:333)
> ... 26 more
